root: true

parser: '@typescript-eslint/parser'

parserOptions:
  tsconfigRootDir: .
  project:
    - './tsconfig.json'
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-hooks'
  - 'jest'

extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jest/recommended'

settings:
  react:
    version: 'detect'

rules:
  'react/prop-types': 
    - off
  '@typescript-eslint/no-unused-vars':
    - "off"
    - varsIgnorePattern: "^_"
  'no-unused-vars':
    - off